#ifndef __DEFS_H__
#define __DEFS_H__


// Audio timer settings

#define AUDIO_TIM TIM2
#define AUDIO_TIM_CLK_ENABLE __HAL_RCC_TIM2_CLK_ENABLE
#define AUDIO_TIM_CHANNEL_GPIO_PORT       __HAL_RCC_GPIOA_CLK_ENABLE
#define AUDIO_TIM_IRQ TIM2_IRQn

#define AUDIO_TIM_GPIO_PORT_CHANNEL1        GPIOA
#define AUDIO_TIM_GPIO_PIN_CHANNEL1         GPIO_PIN_0

// LED
//#define LED_CHUNK 8
#define LED_NUMBER 96

#define LED_DATA_GPIO GPIOB
#define LED_CLK_GPIO GPIOB

#define LED_DATA_GPIO_PIN GPIO_PIN_10
#define LED_CLK_GPIO_PIN GPIO_PIN_11

// Distance sensor

#define DISTANCE_TRIG_GPIO_PIN GPIO_PIN_3
#define DISTANCE_TRIG_GPIO GPIOB
#define DISTANCE_TRIG_GPIO_CLK_ENABLE __HAL_RCC_GPIOB_CLK_ENABLE

#define DISTANCE_ECHO_GPIO_PIN GPIO_PIN_6
#define DISTANCE_ECHO_GPIO GPIOB

#define DISTANCE_TIM TIM4
#define DISTANCE_TIM_CLK_ENABLE __HAL_RCC_TIM3_CLK_ENABLE
#define DISTANCE_TIM_CHANNEL_GPIO_PORT       __HAL_RCC_GPIOA_CLK_ENABLE
#define DISTANCE_TIM_IRQ TIM4_IRQn

#define DISTANCE_UPCLOSE 0
#define DISTANCE_CLOSE 1
#define DISTANCE_FAR 2
#define DISTANCE_NODETECTION 3



// SPI/SPI Flash
#define SPI_CS_GPIO GPIOA
#define SPI_CS_GPIO_PIN 15
#define SPI_GPIO_CLK_ENABLE() /* Already done */


#define SERVO_TIM TIM3
#define SERVO_GPIO GPIOB

#define SERVO_GPIO_PIN_A GPIO_PIN_0
#define SERVO_TIM_CHANNEL_A TIM_CHANNEL_3
#define SERVO_GPIO_PIN_B GPIO_PIN_1
#define SERVO_TIM_CHANNEL_B TIM_CHANNEL_4
#define SERVO_TIM_CLK_ENABLE    __HAL_RCC_TIM3_CLK_ENABLE

/*
 Tampa: 850 -  fechada
 3500 - aberta

 Olho: 900 - fora
       2580- recolhido
 */

#define SERVO_DEFAULT_PULSE_A 3500 /* Caixa aberta */
#define SERVO_DEFAULT_PULSE_B 2580 /* Olho recolhido */

#define SERVO_ENABLE_GPIO GPIOB
#define SERVO_ENABLE_GPIO_PIN GPIO_PIN_4


#define USARTx                           USART1
#define USARTx_CLK_ENABLE()              __HAL_RCC_USART1_CLK_ENABLE();

#define USARTx_FORCE_RESET()             __HAL_RCC_USART1_FORCE_RESET()
#define USARTx_RELEASE_RESET()           __HAL_RCC_USART1_RELEASE_RESET()

/* Definition for USARTx Pins */
#define USARTx_TX_PIN                    GPIO_PIN_9
#define USARTx_TX_GPIO_PORT              GPIOA
#define USARTx_RX_PIN                    GPIO_PIN_10
#define USARTx_RX_GPIO_PORT              GPIOA

#endif
